language: python
sudo: false
cache: pip

python:
  - "3.6"
  - "3.7"

notifications:
  # will post a summary as comment on gihtub in case of failure
  webhooks: https://www.travisbuddy.com/
  on_success: never

branches:
  only:
    - master

before_install:
  - pip install -U pip setuptools wheel
  - pip install -r requirements-test.txt

install:
  - python setup.py -q develop

script:
  # check is done here to allow travis buddy to include a detailed failure summary
  - ./run-qa-checks
  - coverage run -a --source=netjsonconfig runtests.py

after_success:
  coveralls
