language: python
sudo: false
cache: pip

addons:
  apt:
    packages:
      - graphviz

python:
  - "3.5"
  - "3.4"
  - "2.7"

branches:
  only:
    - master

before_install:
  - pip install -U pip setuptools wheel
  - pip install -r requirements-test.txt
  - flake8
  - isort --check-only --recursive .

install:
  - python setup.py -q develop

before_script:
  - mkdir docs/source/_static
  - sphinx-build -W -b html docs/source docs/_build

script:
  - nosetests --with-coverage --cover-package=netjsonconfig

after_success:
  coveralls
